### ISSUE TITLE
Does not compile with FFmpeg 5.0 or earlier

### ISSUE THREAD

**Issue by tongyuantongyu** [vapoursynth/bestsource#11]
`ch_layout` is introduced in FFmpeg 5.1:

```
../src/audiosource.cpp: In constructor 'LWAudioDecoder::LWAudioDecoder(const std::string&, int, int, const std::map<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >&, double)':
../src/audiosource.cpp:156:36: error: 'struct AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
  156 |         AP.Channels = DecodeFrame->ch_layout.nb_channels;
      |                                    ^~~~~~~~~
      |                                    channel_layout
../src/audiosource.cpp:158:26: error: 'struct AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
  158 |         if (DecodeFrame->ch_layout.order == AV_CHANNEL_ORDER_NATIVE) {
      |                          ^~~~~~~~~
      |                          channel_layout
../src/audiosource.cpp:158:45: error: 'AV_CHANNEL_ORDER_NATIVE' was not declared in this scope
  158 |         if (DecodeFrame->ch_layout.order == AV_CHANNEL_ORDER_NATIVE) {
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~
../src/audiosource.cpp:159:45: error: 'struct AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
  159 |             AP.ChannelLayout = DecodeFrame->ch_layout.u.mask;
      |                                             ^~~~~~~~~
      |                                             channel_layout
../src/audiosource.cpp:160:33: error: 'struct AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
  160 |         } else if (DecodeFrame->ch_layout.order == AV_CHANNEL_ORDER_UNSPEC) {
      |                                 ^~~~~~~~~
      |                                 channel_layout
../src/audiosource.cpp:160:52: error: 'AV_CHANNEL_ORDER_UNSPEC' was not declared in this scope
  160 |         } else if (DecodeFrame->ch_layout.order == AV_CHANNEL_ORDER_UNSPEC) {
      |                                                    ^~~~~~~~~~~~~~~~~~~~~~~
../src/audiosource.cpp:161:13: error: 'AVChannelLayout' was not declared in this scope
  161 |             AVChannelLayout ch = {};
      |             ^~~~~~~~~~~~~~~
../src/audiosource.cpp:162:40: error: 'ch' was not declared in this scope
  162 |             av_channel_layout_default(&ch, DecodeFrame->ch_layout.nb_channels);
      |                                        ^~
../src/audiosource.cpp:162:57: error: 'struct AVFrame' has no member named 'ch_layout'; did you mean 'channel_layout'?
  162 |             av_channel_layout_default(&ch, DecodeFrame->ch_layout.nb_channels);
      |                                                         ^~~~~~~~~
      |                                                         channel_layout
../src/audiosource.cpp:162:13: error: 'av_channel_layout_default' was not declared in this scope
  162 |             av_channel_layout_default(&ch, DecodeFrame->ch_layout.nb_channels);
      |             ^~~~~~~~~~~~~~~~~~~~~~~~~
../src/audiosource.cpp: In constructor 'BestAudioSource::CacheBlock::CacheBlock(int64_t, int64_t, AVFrame*)':
../src/audiosource.cpp:269:42: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  269 |         Storage.resize(LineSize * Frame->ch_layout.nb_channels);
      |                                          ^~~~~~~~~
      |                                          channel_layout
../src/audiosource.cpp:272:84: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  272 |             UnpackChannels<uint8_t>(Frame->data[0], Storage.data(), Length, Frame->ch_layout.nb_channels);
      |                                                                                    ^~~~~~~~~
      |                                                                                    channel_layout
../src/audiosource.cpp:274:85: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  274 |             UnpackChannels<uint16_t>(Frame->data[0], Storage.data(), Length, Frame->ch_layout.nb_channels);
      |                                                                                     ^~~~~~~~~
      |                                                                                     channel_layout
../src/audiosource.cpp:276:85: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  276 |             UnpackChannels<uint32_t>(Frame->data[0], Storage.data(), Length, Frame->ch_layout.nb_channels);
      |                                                                                     ^~~~~~~~~
      |                                                                                     channel_layout
../src/audiosource.cpp:278:85: error: 'AVFrame' {aka 'struct AVFrame'} has no member named 'ch_layout'; did you mean 'channel_layout'?
  278 |             UnpackChannels<uint64_t>(Frame->data[0], Storage.data(), Length, Frame->ch_layout.nb_channels);
      |                                                                                     ^~~~~~~~~
      |                                                                                     channel_layout
```

To targets FFmpeg 5.1+ only, then the version requirement should be
```
    dependency('libavcodec', version: '>=59.37.100'),
    dependency('libavformat', version: '>=59.27.100'),
```

**Comment by myrsloik** [comment]
I'll change the requirement to 5.1.x then. As this is kinda experimental still since I want to add rff and such I don't plan on supporting older versions.
